### ISSUE TITLE
Don't wrap banner

### ISSUE THREAD

**Issue by daterdots** [Geocene/TRAINSET#10]
Let's remove this wrapping feature, or at least only make it show up when the window gets very small:
![image](https://user-images.githubusercontent.com/8713574/53585932-e73aa400-3b3b-11e9-8769-65d713b03e71.png)

**Comment by daterdots** [comment]
@rushk014 let's try to be more diligent about referencing which commits fixed which issues. For example, this issue is closed, but there are no references to the commit that fixed it.

**Comment by rushk014** [comment]
@daterdots sorry just realized that was a feature of commit messages, ill be sure to do references in the future
