### ISSUE TITLE
 purple points represent what?

### ISSUE THREAD

**Issue by scut2sjtu** [Geocene/trainset#101]
hi, what do purple points represent?  labeled by some algorithm or rule?
![image](https://user-images.githubusercontent.com/24241777/111431740-20500c00-8737-11eb-9a41-654acd21e43e.png)

**Comment by daterdots** [comment]
It's just a labeled run of points. You can play with the menus in the bottom right to see that there are multiple kinds of labels you can add (which render as different colors), and you can also add different series! 
![image](https://user-images.githubusercontent.com/8713574/111499518-45755800-8700-11eb-86e2-edfc4eb9b9b9.png)
