### ISSUE TITLE
Cannot upload a 5Mb file

### ISSUE THREAD

**Issue by nativv** [Geocene/trainset#109]
I was able to upload a small files (0.5B), but 5Mb just does not work
[accelometer.csv](https://github.com/Geocene/trainset/files/6509115/accelometer.csv)

**Comment by levaphenyl** [comment]
Can you please open the console (inspection tool) in your browser and look for an error?

**Comment by zekeshearer** [comment]
In this case, the error is caused by invalid date formats. Please ensure all dates are in the "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" format, for example "2021-05-17T10:18:02.123Z".
