### ISSUE TITLE
Make it easier to click an individual point

### ISSUE THREAD

**Issue by daterdots** [Geocene/TRAINSET#13]
It's pretty hard to click and individual point - sometimes it seems like I am hovering over the right spot, but then I click and it doesn't work. Just because my curser changes from the crosshairs to the pointer, it doesn't mean that when I click I will hit the point under my pointer.

**Comment by rushk014** [comment]
do you have this issue when there are a lot of points drawn in the window or is it consistent even when zoomed in?

**Comment by daterdots** [comment]
even when I am zoomed in. My cursor will change from the crosshair to the pointer, but when I click, it won't flip until I click closer to the middle of the dot.

**Comment by rushk014** [comment]
i believe this is fixed, let me know if the issue still persists
