### ISSUE TITLE
Plot all series at the same time

### ISSUE THREAD

**Issue by uselessgames** [Geocene/TRAINSET#140]
nice tool. 

wondering if there is a way to view more than two series at the same time? couldnt see in the online demo.  

my example dataset
```
series,timestamp,value,label,
series_a,2019-01-14T16:26:37.000Z,15,
series_b,2019-01-14T16:26:37.000Z,14,
series_c,2019-01-14T16:26:37.000Z,16,
series_d,2019-01-14T16:26:37.000Z,13,
series_e,2019-01-14T16:26:37.000Z,10,
series_f,2019-01-14T16:26:37.000Z,10,
series_a,2019-01-14T16:26:37.100Z,5,
series_b,2019-01-14T16:26:37.100Z,1,
series_c,2019-01-14T16:26:37.100Z,6,
series_d,2019-01-14T16:26:37.100Z,3,
series_e,2019-01-14T16:26:37.100Z,0,
series_f,2019-01-14T16:26:37.100Z,0,

...
```

**Comment by khadijakhaldi** [comment]
did you find an alternative solution for this ?

**Comment by uselessgames** [comment]
@khadijakhaldi yes, https://github.com/EtienneCmb/visbrain

**Comment by daterdots** [comment]
we never supported this feature primarily because it's cumbersome to fit >3 series on a plot if each of the 3 series has very different scales. For example:
* series_a has numbers from 0-1
* series_b has numbers from 0-100
* series_c has numbers from 1000-2000

With 2 series, we can pretty simply do a secondary y axis. Tertiary y axes etc. are possible, but we haven't built that yet. Maybe someone here wants to take that on?

**Comment by khadijakhaldi** [comment]
Thanks @daterdots for the reply! This feature will be useful in applications like anomaly detection in case we have multiple sensors. We need to visualize the state of each sensor at the same timestamp to annotate the anomalies.

**Comment by uselessgames** [comment]
> we never supported this feature primarily because it's cumbersome to fit >3 series on a plot if each of the 3 series has very different scales. For example:
> 
> * series_a has numbers from 0-1
> * series_b has numbers from 0-100
> * series_c has numbers from 1000-2000
> 
> With 2 series, we can pretty simply do a secondary y axis. Tertiary y axes etc. are possible, but we haven't built that yet. Maybe someone here wants to take that on?

why not make each channel have its own amplitude in the tool? 



> Thanks @daterdots for the reply! This feature will be useful in applications like anomaly detection in case we have multiple sensors. We need to visualize the state of each sensor at the same timestamp to annotate the anomalies.

we had same challenge, with visbrain we plot total 10 channels from 3 sensors with no problem.

**Comment by khadijakhaldi** [comment]
@uselessgames the documentation of visbrain http://visbrain.org/ seems not to work, not sure how I can annotate the data !

**Comment by uselessgames** [comment]
you need to create an issue in their repo, I am not the creator nor maintainer. 


-------- Original Message --------
