### ISSUE TITLE
Problem with input data 

### ISSUE THREAD

**Issue by adityamishra-ml** [Geocene/TRAINSET#142]
Hello there,

I was working on a time series data with sampling rate of 1024. I want to classify the data as 0 or 1, I have converted my data to the supported format, but still it is not supported by trainset. I have attached few columns of the data set. can you please help me out with this?
[trainset.csv](https://github.com/Geocene/trainset/files/14310964/trainset.csv)

**Comment by daterdots** [comment]
It looks like the timestamps were not formatted correctly. Add that "T" between the date and time, and add the "Z" at the end. [Here is](https://github.com/Geocene/trainset/files/14316371/fixed_trainet.csv) a fixed CSV (which aliased your timestamps a little but, but it's a start.
<img width="1840" alt="image" src="https://github.com/Geocene/trainset/assets/8713574/eda1cf3d-7d35-4e54-85a7-17d5e45f980a">

**Comment by adityamishraaaa** [comment]
Thank you so much for resolving the issue. It turns out that I mistakenly uploaded the wrong CSV file. The problem actually stemmed from my usage of Pandas to convert the timestamp into ISO8601 format. Interestingly, the solution was quite simple – just adding "T" and "Z" did the trick!

**Comment by adityamishra-ml** [comment]
Thank you so much for resolving the issue. It turns out that I mistakenly uploaded the wrong CSV file. The problem actually stemmed from my usage of Pandas to convert the timestamp into ISO8601 format. Interestingly, the solution was quite simple – just adding "T" and "Z" did the trick!
