### ISSUE TITLE
Does the parser allow more than one filename?

### ISSUE THREAD

**Issue by daterdots** [Geocene/TRAINSET#15]
What happens when someone uploads a CSV where there are multiple values in the `filename` column. Do we allow this? Is there a rational use case for the CSV to be named something other than what's in the `filename` column? Do we want to support some case where someone uploads a CSV called `all_my_files.csv` that has like 20 different filenames (I guess with non-overlapping timestamps?) in it?

Danny's option: the CSV's filename has the match the filename column, and all values in the filename column have to be  the same.

**Comment by rushk014** [comment]
yes, the parser doesn't care about anything in the filename column and just uses the first entry as the actual filename as of right now. i can add checks to make sure all filenames are identical
