### ISSUE TITLE
Set focus width to ~2k data points

### ISSUE THREAD

**Issue by ajaypillarisetti** [Geocene/TRAINSET#16]
On bigger files, like the 32k files, we can set the focus width (the selection in the context) to the entire width. This slows things down. Can we limit the width to a certain number of points?

**Comment by daterdots** [comment]
I agree - you can't "focus" on points that a monitor can't event resolve. So, limiting the width of the  focus section to 2k points max seems like a good idea. I thought @jeremyrcoyle implemented this already?

**Comment by jeremyrcoyle** [comment]
Nope, didn't get to it. Looks like you could do it similar to this: https://bl.ocks.org/mbostock/6232620
. I don't think this should be super high priority though. A user can always just turn it back down once the realize that setting it that way makes it slow.

**Comment by daterdots** [comment]
I guess I agree with @jeremyrcoyle on this one. Maybe we just let users realize it's a bad idea?
