### ISSUE TITLE
"Null" in value column fails on upload

### ISSUE THREAD

**Issue by ajaypillarisetti** [Geocene/TRAINSET#17]
If values in exported files are Null, import fails. Here's a sample file. How do we want to deal with this?
  
[LPG_PK_01_TC_9805_LPGL_20171201_177.lablr.csv.zip](https://github.com/Geocene/TRAINSET/files/2916406/LPG_PK_01_TC_9805_LPGL_20171201_177.lablr.csv.zip)

**Comment by daterdots** [comment]
I think we don't support import of `null` anything (filename, timestamp, value, or label) - if the user has data they want to hide from labeling, just filter out those rows before exporting for trainset
