### ISSUE TITLE
using the "back" button to return to Help results in improperly formatted text

### ISSUE THREAD

**Issue by daterdots** [Geocene/TRAINSET#45]
To reproduce:

- click `sample CSV`
- you will get a broken page
- press back
- the help page looks like this:

![image](https://user-images.githubusercontent.com/8713574/54643327-d18e0f80-4a53-11e9-9f89-cfe86bc9d232.png)

**Comment by rushk014** [comment]
this should be fixed now that the sample csv file was added, let me know if still persists
