### ISSUE TITLE
Import of partially labeled file fails

### ISSUE THREAD

**Issue by ajaypillarisetti** [Geocene/TRAINSET#5]
I partially labeled a 32k datapoint file, downloaded it, and tried to re-upload to continue labeling. Resulted in "Upload Failed | Make sure data is in the TRAINSET format. See help" error.

**Comment by rushk014** [comment]
weird, any chance you could post the partially labeled csv so i can see where it thinks its invalid?

**Comment by ajaypillarisetti** [comment]
oops, sorry - file attached.

[Manjula_GPM_Biomass_33010109_7EE941_India-lablr.csv.zip](https://github.com/Geocene/TRAINSET/files/2907800/Manjula_GPM_Biomass_33010109_7EE941_India-lablr.csv.zip)
