### ISSUE TITLE
Add funder info

### ISSUE THREAD

**Issue by daterdots** [Geocene/TRAINSET#52]

**Comment by daterdots** [comment]
@ajaypillarisetti can you give us the correct organization + grant# to acknowledge?

**Comment by ajaypillarisetti** [comment]
No grant number -- asked for the agreement number. In the interim, let's use this language: This work was supported by the Implementation Science Network of the US National Institutes of Health.

**Comment by daterdots** [comment]
```TRAINSET was supported by the Implementation Science Network of the US National Institutes of Health. The development of SUMSarizer was supported by the Center for Effective Global Action (CEGA) and Innovations for Poverty Action (IPA).```
