### ISSUE TITLE
Resolution of time 

### ISSUE THREAD

**Issue by steffeol** [Geocene/TRAINSET#69]
Hi

I would like to label data where the to-be-labelled part is less than one second. Therefore i would need a resolution of about 20 Hz. I try to upload data with the format 2019-03-13T21:11:29.358Z. However the milliseconds do not get depicted. I was in contact with geocene where they said that it should work. However with the file that i use it does not. Can you help me there? Do do something wrong?

Best wishes

**Comment by daterdots** [comment]
ok, @steffeol - we're on it

**Comment by daterdots** [comment]
![pastedImage](https://user-images.githubusercontent.com/8713574/79005212-36a71e00-7b0b-11ea-8efe-660151fff13f.png)

[Test-Trainset-69-bug.csv.zip](https://github.com/Geocene/TRAINSET/files/4462344/Test-Trainset-69-bug.csv.zip)

**Comment by daterdots** [comment]
Two issues will need to be fixed: we need to fix the chart and the exports

**Comment by steffeol** [comment]
Wow thanks for the effort! Looking forward to the progress! Will help me a lot!

**Comment by daterdots** [comment]
@rushk014 - let's start with this one

**Comment by steffeol** [comment]
Hi, I don't now what that means. are you working on the issue?
Thank you for the response.

**Comment by daterdots** [comment]
@steffeol yes, we are working on this

**Comment by steffeol** [comment]
So I see that this is closed now, but it still does not work with the format 2019-03-13T21:11:29.358Z.

**Comment by rushk014** [comment]
@steffeol so I've fixed it on the github repo but am holding off to push it to the live website as I'm working out some kinks with the labeler tool

**Comment by daterdots** [comment]
@rushk014 let's get in the habit of making sure that `master` always matches what's deployed - make these kinds of changes on another branch

**Comment by daterdots** [comment]
and close the issue when it's deployed

**Comment by daterdots** [comment]
@steffeol here's your data running locally - we will deploy this soon 
![image](https://user-images.githubusercontent.com/8713574/88336640-36154a80-ccea-11ea-80f9-b27a164e09cb.png)

**Comment by steffeol** [comment]
Nice! Thank you guys! looking forward to it!

**Comment by daterdots** [comment]
@steffeol this change is now live

**Comment by daterdots** [comment]
@steffeol did this work out for you?
