### ISSUE TITLE
"Clear labels" results in unexpected behavior

### ISSUE THREAD

**Issue by daterdots** [Geocene/TRAINSET#7]
Just after pressing "Clear" -- looks as expected
![image](https://user-images.githubusercontent.com/8713574/53584964-b5284280-3b39-11e9-98b2-16379a839c60.png)

Scroll focus window one half screen to the right, and now we see some uncleared labels
![image](https://user-images.githubusercontent.com/8713574/53585002-c8d3a900-3b39-11e9-891d-e9d70c1498dd.png)

**Comment by daterdots** [comment]
I think I see what's happening: I think the "clear labels" button is, in fact, clearing labels for the _drawn_ points in the bottom context bar, but it is _not_ clearing any of the points that were downsampled out.

**Comment by rushk014** [comment]
can't seem to recreate it but i changed the logic handling clear, let me know if this persists

**Comment by daterdots** [comment]
Whatever you did seems to have fixed it
