### ISSUE TITLE
File upload takes forever

### ISSUE THREAD

**Issue by minhduc0711** [Geocene/trainset#70]
I'm having problems uploading this csv file: https://pastebin.com/raw/s8hzER8g.
Strangely, if I delete the last line row, it would load successfully.
Any ideas what's happening? Thanks in advance.

**Comment by daterdots** [comment]
Whoa, weird! I do notice that your file has _exactly_ 100 observations. @rushk014 - do we do something special in particular when files are <100 vs >100 observations? I bet it's some sort of weird edge case with how we render the context bar (or something like that).
