### ISSUE TITLE
Upload failed on 3E5 data points

### ISSUE THREAD

**Issue by daterdots** [Geocene/TRAINSET#9]
Is one of the format rules that the dataset needs to have fewer rows than a certain threshold, or is this 3E5 dummy_input dataset improperly formatted?

![image](https://user-images.githubusercontent.com/8713574/53585696-5ebc0380-3b3b-11e9-920e-8f335581138a.png)

**Comment by rushk014** [comment]
could you attach the csv that fails?

**Comment by rushk014** [comment]
there isn't any row restriction

**Comment by daterdots** [comment]
I changed the extension to .txt so that GitHub would accept it 

[dummy-input-length-3e+05.txt](https://github.com/Geocene/TRAINSET/files/2916878/dummy-input-length-3e%2B05.txt)
