### ISSUE TITLE
Super long series messes up chart formatting

### ISSUE THREAD

**Issue by rushk014** [Geocene/trainset#93]
![Screen Shot 2020-10-14 at 5 31 23 PM](https://user-images.githubusercontent.com/29556139/96059551-1a31c880-0e43-11eb-86ed-9bf8eed8284f.png)

**Comment by rushk014** [comment]
@daterdots should we enforce some kind of restriction on valid series names? right now there is no input validation for that entire column

**Comment by daterdots** [comment]
nah - if folks want to have crazy-long series names, they will see this. And then they will change their series name. I wouldn't worry about it for now.

**Comment by rushk014** [comment]
@daterdots added all the things we were talking about, feel free to take a look!
